apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
  finalizers:
    - resources-finalizers.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: 'git@github.com:achrefbenmbarek1/libraryManagementAppOfApps.git'
    targetRevision: main
    path: .
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
