apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: back-library-app
  namespace: argocd
  finalizers:
    - resources-finalizers.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: 'git@github.com:achrefbenmbarek1/back-bibliotheque.git'
    targetRevision: main
    path: ./
  syncPolicy:
    automated:
      prune: true  # Remove resources that are no longer defined in the Git repository
      selfHeal: true # Automatically apply changes detected in the Git repository
    syncOptions:
      - CreateNamespace=true

