apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: back-library-claim-app
  annotations:
    argocd-image-updater.argoproj.io/image-list: myalias=achrefbenmbarek123159/arm
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/ssh-private-key
    argocd-image-updater.argoproj.io/git-branch: main
    # argocd-image-updater.argoproj.io/myalias.allow-tags: regexp:^backend-[0-9]+\.[0-9]+\.[0-9]+$
    argocd-image-updater.argoproj.io/myalias.allow-tags: backend-0.0.9
    argocd-image-updater.argoproj.io/myalias.update-strategy: semver
    argocd-image-updater.argoproj.io/myalias.kustomize.path: spec.image
    argocd-image-updater.argoproj.io/myalias.kustomize.image-name: achrefbenmbarek123159/arm
    # argocd-image-updater.argoproj.io/myalias.credentials: pullsecret:backend/harbor-registry-secret
    argocd-image-updater.argoproj.io/myalias.force-update: "true"

  namespace: argocd
  finalizers:
    - resources-finalizers.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  ignoreDifferences:
  - group: "example.org"
    kind: BackendApplication
  source:
    repoURL: 'git@github.com:achrefbenmbarek1/libraryManagementBackConfig.git'
    targetRevision: main
    path: ./back-app/backend
    # kustomize: {}
    # directory:
    #   recurse: true
    kustomize:
      images:
        - "achrefbenmbarek123159/arm=spec.image"
  syncPolicy:
    automated:
      prune: false  # Remove resources that are no longer defined in the Git repository
      selfHeal: true # Automatically apply changes detected in the Git repository
    syncOptions:
      - CreateNamespace=true
      # - SkipDryRunOnMissingResource=true

